import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

import Header from "../components/Header";
import Main from "../components/Main";
export default function Home() {
  const router = useRouter();
  // const { status } = useSession({
  //   required: true,
  //   onUnauthenticated() {
  //     //The user is not authenticated, handle it here.
  //     router.push("/home");
  //   },
  // });
  // console.log("isAuthenticated?", status);
  return (
    <div className="bg-[#F3F2EF] dark:bg-black dark:text-white h-screen overflow-y-scroll md:space-y-6">
      <Head>
        <title>Feed | LinkedIn</title>
        <meta name="LinkedIn Clone" content="Generated by next app" />
      </Head>
      {/**Header */}
      <Header />
      {/**Main Content */}
      <Main />
    </div>
  );
}
export async function getServerSideProps(context) {
  //check if the user is authenticated on the server..
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: "/home",
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}
